name: darkstorm_common
description: Common widgets and utilities for my apps
version: 1.0.1
repository: https://github.com/CalebQ42/darkstorm-common
homepage: https://darkstorm.tech

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.4
  extension_google_sign_in_as_googleapis_auth: ^2.0.10
  googleapis: ^11.2.0
  universal_internet_checker: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
