name: darkstorm_common
description: Common widgets and utilities for my apps
version: 2.0.3
repository: https://github.com/CalebQ42/darkstorm-common
homepage: https://darkstorm.tech

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  googleapis: ">=13.2.0"
  internet_connection_checker_plus: ^2.7.0
  platform_info: ^5.0.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
